### PR TITLE
Refactor KiD driver, add precipitation analysis

### PR DESCRIPTION
**Pull request by mikhailmints**
## Purpose 

To analyze precipitation susceptibility in the KiD model and compare it to expected results.

## Content

- Wrapped the code in `KiD_driver.jl` inside a function so it can be more easily called from somewhere other than the command line.
- Added profiles of precipitation susceptibility from autoconversion and accretion to final aux profiles, using functions from `CloudMicrophysics.jl`
- Added file for analyzing precipitation susceptibility from prescribed Nd by running the KiD simulation multiple times and computing finite differences, relying on a simple precipitation production metric summing `ρq_rai` over time at the height of the cloud base.
- Incorporated the changes from `mm/command_line_args_types`, changing `arg_type` of arguments to `Float64` instead of `Real` and adding the option to select `Float64` or `Float32` as the float type.

----
- [x] I have read and checked the items on the review checklist.

### CODE REVIEW

**Review by sajjadazimi — COMMENTED** [review]
Some buildkite jobs fail. Seems like there are some minor issues. Otherwise it looks good to me. Please squash you commits when it's ready to get merged.

**Review by sajjadazimi — APPROVED** [review]
Looks good to me. Just update the version in Project.toml (increment the patch number) and squash your commits.

**Comment by sajjadazimi** [comment]
bors try

**Comment by trontrytel** [comment]
bors try

**Pull request merged**
