### PR TITLE
Initial condition fixes

### LINKED ISSUE #36: Fix moist initial condition tests

### PR DESCRIPTION
**Pull request by trontrytel**
This PR works toward making the initial condition between PySDM and KiD.jl the same.

Fixes #36

### CODE REVIEW

**Comment by trontrytel** [comment]
init_profile

**Comment by sajjadazimi** [comment]
Thanks a lot! It looks very good.

By the way, I noticed that the small difference in T profile comes from the tiny difference in rho profile (you can check by passing SDM_rho instead of rho profile to KiD.init_1d_column). And I think the tiny difference in rho profile might come from different ODE solvers.

**Review by sajjadazimi — APPROVED** [review]

**Comment by trontrytel** [comment]
> Thanks a lot! It looks very good.
> 
> By the way, I noticed that the small difference in T profile comes from the tiny difference in rho profile (you can check by passing SDM_rho instead of rho profile to KiD.init_1d_column). And I think the tiny difference in rho profile might come from different ODE solvers.

Thank you for tracking down the density differences @sajjadazimi !

I'll check if switching to a different solver for the initial value problem would bring us closer.

**Pull request merged**
